# Generated by Django 2.1.5 on 2019-02-13 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0007_auto_20190213_2335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('status', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('is_recommend', models.BooleanField(default=False, help_text='是否推荐', verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
