# Generated by Django 2.1.5 on 2019-02-05 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifyCode',
            new_name='EmailVerifyRecord',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='user/avatar/image/%Y/%m', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subcribe',
            field=models.BooleanField(blank=True, default=True, help_text='除验证码通知邮件外的通知邮件', verbose_name='是否订阅通知邮件'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
