# Generated by Django 2.1.5 on 2019-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190205_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱'), ('comment', '评论')], help_text='验证码类型', max_length=15, null=True, verbose_name='验证码类型'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='头像', null=True, upload_to='users/images/', verbose_name='头像'),
        ),
    ]
