# Generated by Django 2.1.5 on 2019-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190205_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='添加时间', null=True, verbose_name='添加时间'),
        ),
    ]
