# Generated by Django 2.1.5 on 2019-02-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverifyrecord_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='send_time',
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, help_text='发送时间', null=True, verbose_name='发送时间'),
        ),
    ]
