# Generated by Django 2.1.5 on 2019-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190212_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_subcribe',
            field=models.BooleanField(blank=True, default=False, help_text='除验证码通知邮件外的通知邮件', verbose_name='是否订阅通知邮件'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='用户名'),
        ),
    ]
