# Generated by Django 2.1.5 on 2019-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190213_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
