# Generated by Django 2.1.5 on 2019-02-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190213_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_active',
            field=models.BooleanField(default=True, help_text='验证码状态', verbose_name='验证码状态'),
        ),
    ]
