# Generated by Django 2.1.5 on 2019-03-17 23:55

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', froala_editor.fields.FroalaField(help_text='文章内容', verbose_name='文章内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击量')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, help_text='排序', unique=True, verbose_name='排序')),
                ('cate_level', models.CharField(choices=[('1', '一级类目'), ('2', '二级类目')], default='', help_text='分类级别', max_length=10, verbose_name='分类级别')),
                ('name', models.CharField(default='', help_text='分类名', max_length=30, verbose_name='分类名')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', limit_choices_to={'cate_level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='articles.ArticlesCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.ArticlesCategory', verbose_name='类别'),
        ),
    ]
