# Generated by Django 2.1.5 on 2019-02-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('desc', models.TextField(blank=True, help_text='类别描述', null=True, verbose_name='类别描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(blank=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.ArticlesCategory', verbose_name='类别'),
        ),
    ]
