# Generated by Django 2.1.5 on 2019-02-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190206_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否激活', verbose_name='是否激活'),
        ),
    ]
