# Generated by Django 2.1.5 on 2019-02-08 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='articles.ArticlesCategory', verbose_name='父类目级别'),
        ),
    ]
