# Generated by Django 2.1.5 on 2019-02-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190209_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='pub_time',
            field=models.DateField(blank=True, null=True, verbose_name='添加时间'),
        ),
    ]
