# Generated by Django 2.1.5 on 2019-02-15 22:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190213_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='文章内容', verbose_name='文章内容'),
        ),
    ]
