# Generated by Django 2.1.5 on 2019-02-15 22:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190215_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='文章内容', verbose_name='文章内容'),
        ),
    ]
